### ISSUE TITLE
Slow startup time

### ISSUE THREAD

**Issue by kklarme** [ClockworkOrigins/Spine#2]
Hello there,

first of all, thank you for your amazing work and this nice piece of software.

For some time, Spine takes quite a while for its initial startup. This problem only occurs in online mode. More on this below.

I've done some testing with the code myself and realized the following problems:

1.  When the application is initialized and a user is logged in, [`ILauncher::tryCleanCaches`](https://github.com/ClockworkOrigins/Spine/blob/9bb0908a1beaaa5b5e4ad59f0d1ac8b973945fd1/src/client/launcher/ILauncher.cpp#L531) is called.\
There, the savegames of the `fixes.db` are loaded and for every entry, a single request is sent to the server.\
This causes a lot of overhead which could be avoided by sending all entries in a single request.\
The more save games a user has, the longer the startup will take with the current setup.

2. [`ILauncher::loginChanged`](https://github.com/ClockworkOrigins/Spine/blob/9bb0908a1beaaa5b5e4ad59f0d1ac8b973945fd1/src/client/launcher/ILauncher.cpp#L108) is called for every launcher that is registered.\
At the moment, there are four registered launchers as can be seen [here](https://github.com/ClockworkOrigins/Spine/blob/9bb0908a1beaaa5b5e4ad59f0d1ac8b973945fd1/src/client/launcher/LauncherFactory.cpp#L34).\
This causes [`ILauncher::tryCleanCaches`](https://github.com/ClockworkOrigins/Spine/blob/9bb0908a1beaaa5b5e4ad59f0d1ac8b973945fd1/src/client/launcher/ILauncher.cpp#L531) to be called multiple times which causes further delays because of issue 1.\
Depending on the requirements here, it could be useful to only call `tryCleanCaches` and `synchronizeOfflineData` once.

I don't have a lot of knowledge of C++ but I could try to make the suggested changes and open a PR if you want. 

On a sidenote, it might make sense to not store the password in cleartext but rather work with hashes.

Edit: Added sidenote

**Comment by BonneCW** [comment]
Thanks for reporting. I created an internal ticket for it (SP-1223) and will fix it soon.

**Comment by kklarme** [comment]
Hey there, I just saw you publishing 1.38 which included a fix for the previously mentioned bug. It seems to be fixed now.

Thank you for your work again!

**Comment by BonneCW** [comment]
Yeah, should be fine now, especially with the server side fix I did today. There is another small fix I did also today, but that one will be part of the next update.
